### ISSUE TITLE
regarding code for inference

### ISSUE THREAD

**Issue by Jeba-create** [deeplearning-wisc/stud#1]
Thank you so much for such a great work.
Could you please share the sample code to do inference on new video samples?

**Comment by d12306** [comment]
hi, thanks for your appreciation! @Jeba-create 
stud does not evaluate on videos, if you want to evaluate on videos, then you can feed single frames in order to stud to get the ood detection performance. that being said, you have to make sure clearly the objects in videos are belonging to id or ood. 

for single-frame inference, you can refer to detectron2 doc https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5 for additional implementation.
